tasks:
  - name: Odoo Setup
    init: |
      mkdir -p addons config
      docker-compose build
    command: |
      docker-compose up -d
      gp ports await 8069
      echo "Odoo está corriendo en $(gp url 8069)"
      docker-compose logs -f

ports:
  - port: 8069
    name: Odoo
    description: Interfaz web de Odoo
    onOpen: open-preview
    visibility: public
  - port: 5432
    name: PostgreSQL
    description: Base de datos PostgreSQL
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
