image: gitpod/workspace-full

tasks:
  - name: Setup Odoo
    init: |
      sudo apt-get update
      sudo apt-get install -y docker-compose
      docker-compose -f docker-compose.yml up -d --build
    command: |
      docker ps
      echo "Odoo está iniciando..."

ports:
  - port: 8069
    onOpen: open-preview
